<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0bb365aa-cbaa-4c82-b8b2-344320f3b809</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sample.GraphQL.Application\Sample.GraphQL.Application.csproj" />
    <ProjectReference Include="..\Sample.GraphQL.DataModel\Sample.GraphQL.Persistence.csproj" />
  </ItemGroup>

</Project>
