<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="HotChocolate.AspNetCore" Version="15.1.12" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Sample.GraphQL.DataModel\Sample.GraphQL.Persistence.csproj" />
	  <ProjectReference Include="..\Sample.GraphQL.Domain\Sample.GraphQL.Domain.csproj" />
	</ItemGroup>

</Project>
